# Generated by Django 5.0.6 on 2024-07-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_message_options_message_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='lastRead',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
