# Generated by Django 5.0.1 on 2024-02-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='suna-onne.jpg', null=True, upload_to=''),
        ),
    ]
